const SYMBOL_KEYS=['pumpkin','ghost','bat','cauldron','castle','10','J','Q','K','A','wild','scatter','bonus'];
// Only use animation frames that exist in assets/animations.
const WIN_FRAMES=[0,1,2,3,7,9,10].map(i=>`pumpkin-win-${i}`);
const PAYLINES=[[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2],[0,0,1,2,2],[2,2,1,0,0],[1,0,0,0,1],[1,2,2,2,1],[1,0,1,0,1],[1,2,1,2,1],[0,1,1,1,0],[2,1,1,1,2],[0,1,0,1,0],[2,1,2,1,2],[1,1,0,1,1],[1,1,2,1,1],[0,0,2,0,0],[2,2,0,2,0],[0,2,0,2,0]];
const LINE_COLORS=['#eab308','#38bdf8','#f43f5e','#a855f7','#22c55e','#fb923c','#06b6d4','#ec4899','#84cc16','#f59e0b','#14b8a6','#6366f1','#d946ef','#e11d48','#10b981','#facc15','#38bdf8','#c084fc','#4ade80','#f472b6'];
const $=id=>document.getElementById(id);let balance=10000,bet=50,jackpot=75420,lines=25,spinning=false,scene;
function setText(){$('balance').textContent=balance;$('bet').textContent=bet;$('lines').textContent=lines;$('jackpot').textContent=jackpot}
function rand(){return Math.floor(Math.random()*SYMBOL_KEYS.length)}
function evaluateWins(values){const wins=[];PAYLINES.forEach((path,line)=>{const ids=path.map((row,col)=>values[col+row*5]);const first=ids[0];let count=0;for(const id of ids){if(id===first||id===10||first===10)count++;else break}if(count>=3)wins.push({line,count,amount:bet*(count-2)*2,positions:path.slice(0,count).map((row,col)=>col+row*5)})});return wins.sort((a,b)=>b.amount-a.amount)}
class SlotScene extends Phaser.Scene{
 constructor(){super('SlotScene');this.symbols=[];this.overlays=[];this.fx=[];this.grid=[];this.payline=null;this.spinId=0;this.lastLayout={w:0,h:0}}
 preload(){SYMBOL_KEYS.forEach(k=>this.load.image(k,`assets/symbols/${k}.webp`));WIN_FRAMES.forEach(k=>this.load.image(k,`assets/animations/${k}.webp?v=20260920-2`))}
 create(){scene=this;this.makeGrid();this.scale.on('resize',()=>this.layout());this.layout();this.events.on('shutdown',()=>this.clearPayline())}
 makeGrid(){for(let i=0;i<15;i++){const t=this.add.image(0,0,SYMBOL_KEYS[rand()]).setOrigin(.5);const glow=this.add.graphics();glow.fillStyle(0x8dff4a,.42);glow.fillCircle(0,0,58);glow.setVisible(false);const overlay=this.add.image(0,0,WIN_FRAMES[0]).setOrigin(.5).setAlpha(0);this.symbols.push(t);this.fx.push(glow);this.overlays.push(overlay);this.grid.push(rand())}}
 layout(){const w=this.scale.width,h=this.scale.height;this.lastLayout={w,h};this.symbols.forEach((t,i)=>{const x=((i%5)+.5)*w/5,y=(Math.floor(i/5)+.5)*h/3,size=Math.min(w/5,h/3)*.78;t.x=x;t.y=y;t.setScale(Math.min(size/t.width,size/t.height));this.fx[i].setPosition(x,y);const o=this.overlays[i];o.setPosition(x,y);o.setScale(Math.min(size*1.22/o.width,size*.9/o.height))})}
 baseY(index){return (Math.floor(index/5)+.5)*this.scale.height/3}
 animatePumpkin(i){const overlay=this.overlays[i],glow=this.fx[i],fitFrame=frame=>{overlay.setTexture(frame);const cell=Math.min(this.scale.width/5,this.scale.height/3)*.82;overlay.setScale(Math.min(cell/overlay.width,cell/overlay.height))};fitFrame(WIN_FRAMES[0]);overlay.setAlpha(1);glow.setVisible(true).setAlpha(.75).setScale(.55);this.tweens.add({targets:glow,scale:1.25,alpha:0,duration:900,ease:'Sine.easeOut',onComplete:()=>glow.setVisible(false)});WIN_FRAMES.forEach((frame,n)=>this.time.delayedCall(n*35,()=>fitFrame(frame)));this.time.delayedCall(560,()=>overlay.setAlpha(0))}
 clearPayline(){if(this.payline){this.payline.destroy();this.payline=null}}
 showPayline(n){this.clearPayline();const g=this.add.graphics();const color=Phaser.Display.Color.HexStringToColor(LINE_COLORS[n%20]).color;const p=PAYLINES[n%20],w=this.scale.width,h=this.scale.height;const pts=p.map((r,c)=>({x:(c+.5)*w/5,y:(r+.5)*h/3}));g.lineStyle(12,color,.32);g.beginPath();g.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(q=>g.lineTo(q.x,q.y));g.strokePath();g.lineStyle(3.5,0xffffff,1);g.beginPath();g.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(q=>g.lineTo(q.x,q.y));g.strokePath();pts.forEach(q=>{g.fillStyle(color,1);g.fillCircle(q.x,q.y,6);g.fillStyle(0xffffff,1);g.fillCircle(q.x,q.y,2.5)});this.payline=g;this.time.delayedCall(1900,()=>this.clearPayline())}
 spin(){if(spinning||balance<bet)return;spinning=true;balance-=bet;jackpot+=Math.max(1,Math.floor(bet*.1));setText();this.clearPayline();const id=++this.spinId,stopped=[false,false,false,false,false],values=Array(15).fill(0),started=performance.now();let lastCycle=-1;this.symbols.forEach(t=>{t.setTint(0xffffff);this.tweens.killTweensOf(t)});this.overlays.forEach(t=>t.setAlpha(0));this.fx.forEach(t=>t.setVisible(false));
  const stopColumn=col=>{stopped[col]=true;for(let r=0;r<3;r++){const index=col+r*5;values[index]=rand();this.symbols[index].setTexture(SYMBOL_KEYS[values[index]]);this.tweens.add({targets:this.symbols[index],y:this.baseY(index),duration:260,ease:'Back.easeOut'})}};
  const tick=()=>{if(id!==this.spinId)return;const elapsed=performance.now()-started;for(let c=0;c<5;c++)if(!stopped[c]&&elapsed>=850+c*300)stopColumn(c);const cycle=Math.floor(elapsed/75);if(cycle!==lastCycle){lastCycle=cycle;for(let c=0;c<5;c++)if(!stopped[c])for(let r=0;r<3;r++){const index=c+r*5;values[index]=rand();this.symbols[index].setTexture(SYMBOL_KEYS[values[index]])}}
    for(let c=0;c<5;c++)if(!stopped[c])for(let r=0;r<3;r++){const index=c+r*5,cell=this.scale.height/3,phase=(elapsed*1.35+r*cell/2)%cell;this.symbols[index].y=this.baseY(index)+phase-cell/2}
    if(stopped.every(Boolean)){this.grid=values.slice();spinning=false;const wins=evaluateWins(values),best=wins[0];if(best){balance+=best.amount;$('win').textContent=best.amount;this.showPayline(best.line);best.positions.forEach(index=>{this.symbols[index].setTint(0xc6ff50);if(values[index]===0)this.animatePumpkin(index)})}else $('win').textContent=0;setText();return}this.time.delayedCall(35,tick)};tick()}
}
const config={type:Phaser.AUTO,parent:'reels',backgroundColor:'rgba(0,0,0,0)',transparent:true,render:{antialias:true,powerPreference:'high-performance'},scale:{mode:Phaser.Scale.RESIZE,width:'100%',height:'100%'},scene:SlotScene};new Phaser.Game(config);$('spin').onclick=()=>scene?.spin();$('plus').onclick=()=>{bet=Math.min(500,bet+25);setText()};$('minus').onclick=()=>{bet=Math.max(25,bet-25);setText()};document.querySelector('.bet').onclick=()=>{bet=bet>=500?25:bet+25;setText()};$('lineUp').onclick=()=>{lines=Math.min(25,lines+5);setText()};$('lineDown').onclick=()=>{lines=Math.max(20,lines-5);setText()};document.querySelector('.lines').onclick=()=>{lines=lines===25?20:25;setText()};$('menu').onclick=()=>alert(`Halloween Spins\nLíneas activas: ${lines}\nApuesta: $${bet}`);setText();

